name: courier_delivery
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  connectivity_plus: ^6.0.3
  shared_preferences: ^2.2.3
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  country_pickers: ^3.0.1
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  pin_code_fields: ^8.0.1
  sms_autofill: ^2.3.0
  pin_input_text_field: ^4.5.1
  colorful_safe_area: ^1.0.0
  pinput: ^4.0.0
  intl: ^0.19.0
  timelines: ^0.1.0
  percent_indicator: ^4.2.3
  fluttertoast: ^8.2.2
  expandable_text: ^2.3.0
  flutter_svg_provider: ^1.0.7
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assetss/locales/
  fonts:
    - family: SF Pro Text
      fonts:
        - asset: assets/fonts/SFProTextBold.ttf
          weight: 700
        - asset: assets/fonts/SFProTextSemibold.ttf
          weight: 600
        - asset: assets/fonts/SFProTextRegular.ttf
          weight: 400
        - asset: assets/fonts/SFProTextMedium.ttf
          weight: 500
    - family: Proxima Nova
      fonts:
        - asset: assets/fonts/ProximaNovaBold.ttf
          weight: 700
    - family: Avenir
      fonts:
        - asset: assets/fonts/AvenirRegular.ttf
          weight: 400
        - asset: assets/fonts/AvenirHeavy.ttf
          weight: 900
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SFProDisplayBold.ttf
          weight: 700
        - asset: assets/fonts/SFProDisplayRegular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplaySemibold.ttf
          weight: 600
    - family: Manrope
      fonts:
        - asset: assets/fonts/ManropeMedium.ttf
          weight: 500
    - family: Outfit
      fonts:
        - asset: assets/fonts/OutfitRegular.ttf
          weight: 400
flutter_intl:
  enabled: true
